<?php 
    header("Access-Control-Allow-Origin: *");
    header("Content-type: application/json; charset=utf-8");


    $path = "http://localhost/VaporStore_web/";

    $game[1] = array(
        "id" => 1,
        "title" => "Red Dead Redemption 2",
        "description" => "Red Dead Redemption 2, a épica aventura de mundo aberto da Rockstar Games aclamada pela crítica e o jogo mais bem...",
        
        "descriptionMid" => "Red Dead Redemption 2, a épica aventura de mundo aberto da Rockstar Games aclamada pela crítica e o jogo mais bem avaliado desta geração de consoles, agora chega aprimorado para PC com conteúdos inéditos no Modo História, melhorias visuais e muito mais.",
        "descriptionFull" => "Estados Unidos, 1899.
Arthur Morgan e a gangue Van der Linde são bandidos em fuga. Com agentes federais e os melhores caçadores de recompensas no seu encalço, a gangue precisa roubar, assaltar e lutar para sobreviver no impiedoso coração dos Estados Unidos. Conforme divisões internas profundas ameaçam despedaçar a gangue, Arthur deve fazer uma escolha entre os seus próprios ideais e a lealdade à gangue que o criou.
Agora com conteúdo adicional no Modo História e um Modo Foto repleto de recursos, Red Dead Redemption 2 também inclui acesso gratuito ao mundo compartilhado de Red Dead Online. Nele, os jogadores assumem uma diversidade de ofícios para construir suas próprias trajetórias na fronteira, seja perseguindo criminosos procurados como Caçador de Recompensa, estabelecendo um negócio como Mercador, escavando tesouros exóticos como Colecionador ou operando uma destilaria subterrânea como Moonshiner, e muito mais.
Com novas melhorias gráficas e técnicas que tornam o jogo mais imersivo, Red Dead Redemption 2 para PC aproveita ao máximo a potência do PC para dar vida a cada canto deste mundo gigantesco, rico e detalhado, incluindo maiores distâncias de renderização; iluminação global de maior qualidade e oclusão do ambiente para melhorar a iluminação do dia e da noite; melhorias nos reflexos e sombras mais fortes e de maior resolução a todas as distâncias; texturas de árvore tesseladas e melhorias nas texturas de grama e pelo, tornando todas as plantas e animais mais realistas.
Red Dead Redemption 2 para PC também oferece suporte a HDR e a monitores de ponta com resolução 4K ou superior, configurações com vários monitores, widescreen, taxas de quadros mais rápidas, entre outras opções.",

        "logoGame01" => "{$path}img/banners/rd2/logoGame01.jpg",
        "banner01" => "{$path}img/banners/rd2/banner01.jpg",
        "banner02" => "{$path}img/banners/rd2/banner02.jpg",
        "screenShot01" => "{$path}img/banners/rd2/screenshot01.jpg",
        "screenShot02" => "{$path}img/banners/rd2/screenshot02.jpg",
        "screenShot03" => "{$path}img/banners/rd2/screenshot03.jpg",
        "screenShot04" => "{$path}img/banners/rd2/screenshot04.jpg",
        "video01" => "",
        "category" => "Ação",
        "categoryLink" => "action",
        "modoJogo" => "Um jogador",
        "multiplayer" => "Cooperativo on-line",
        "controls" => "Teclado, Controles",
    
        "CPU_Min" => "Intel® Core™ i7-4770K / AMD Ryzen 5 1500X",
        "GPU_Min" => "Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB",
        "storage_Min" => "150 GB",
        "memory_Min" => "12gb RAM",
        "SO_Min" => "Windows 10 64-bit",
        "OBS_Min" => "SSD Recomendado",
    
        "CPU_Recomendate" => "Intel® Core™ i7-4770K / AMD Ryzen 5 1500X",
        "GPU_Recomendate" => "Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB",
        "storage_Recomendate" => "150 GB",
        "memory_Recomendate" => "16gb RAM",
        "SO_Recomendate" => "Windows 10 64-bit",
        "OBS_Recomendate" => "SSD Requisitado",
    
        "price" => "R$ 299,90",
        "promo" => "",
        "promoLabel" => "",
        "plataform" => "PC, Xbox Series, PS5",
        "analisesBoa" => "Muito Positivas",
        "analisesNeutra" => "",
        "analisesRuim" => "",
        "privacity" => "https://www.rockstargames.com/br/privacy",
        "userAccept" => "https://www.rockstargames.com/br/legal",
        "pegiInfo" => "18+",
    
        "analise1_img" => "{$path}img/analise01.jpg",
        "analise1_userName" => "Jznkk",
        "analise1_recomendacao" => "Recomendado",
        "analise1_naoRecomendacao" => "",
        "analise1_recomendacaoRuim" => "",
        "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise1_data" => "17 DE JUNHO",
        "analise1_descricao" => "Red Dead Redemption 2 é um jogo extraordinário que redefine os padrões de jogos de mundo aberto. A narrativa envolvente de Arthur Morgan e a gangue Van der Linde, combinada com personagens complexos, oferece uma experiência emocionalmente ressonante. O mundo aberto é deslumbrante e detalhado, com paisagens vastas e vida selvagem dinâmica. A jogabilidade é fluida e diversificada, com missões principais emocionantes e atividades secundárias imersivas. Os gráficos e o som são de alta qualidade, capturando perfeitamente a essência do Velho Oeste. Este jogo é uma experiência imperdível para qualquer fã de jogos de aventura.",
    
        "analise2_img" => "{$path}img/analise02.jpg",
        "analise2_userName" => "gucY",
        "analise2_recomendacao" => "Recomendado",
        "analise2_naoRecomendacao" => "",
        "analise2_recomendacaoRuim" => "",
        "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise2_data" => "30 DE MAIO",
        "analise2_descricao" => "Simplesmente o melhor jogo que eu já tive o prazer de jogar, falo isso com nenhum peso na consciência. É algo inexplicavelmente bem feito e polido, todas ações, locais, físicas e diálogos, tudo com uma maestria de brilhar os olhos. A construção de mundo, roteiro e personagem é algo realmente digno de premiação como o Oscar. Compra, isso é uma experiência riquíssima e que com certeza você nunca vai esquecer.",
    
        "analise3_img" => "{$path}img/analise03.jpg",
        "analise3_userName" => "Alyszun",
        "analise3_recomendacao" => "Recomendado",
        "analise3_naoRecomendacao" => "",
        "analise3_recomendacaoRuim" => "",
        "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise3_data" => "15 DE JUNHO",
        "analise3_descricao" => "Amei a gameplay de Red Dead Redemption 2, mas odiei o jogo por nos fazer apegar tanto ao Arthur Morgan e depois matá-lo na nossa frente, sem chance de ajudá-lo. Nunca senti uma tristeza tão grande assim dentro de um game.",
    
        "analise4_img" => "{$path}img/analise04.jpg",
        "analise4_userName" => "2hAz",
        "analise4_recomendacao" => "Recomendado",
        "analise4_naoRecomendacao" => "",
        "analise4_recomendacaoRuim" => "",
        "analise4_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise4_data" => "3 DE JUNHO",
        "analise4_descricao" => "Red Dead Redemption 2 é O MELHOR jogo modo historia que eu ja joguei, gráficos incríveis e detalhes impressionantes. A história de Arthur Morgan e as relações na gangue Van der Linde me prenderam do começo ao fim. Adorei a variedade de coisas para fazer, como caçar, pescar e explorar, que fizeram o jogo parecer real e cheio de liberdade.",
    
        "gameLink" => "https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/",
        "realeaseDate" => "5/dez./2019",
        "distributor" => "Rockstar Games",
        "distributorSite" => "https://www.rockstargames.com/br/",
        "creator" => "Rockstar Games",
        "creatorName" => "Rockstar Games",
        "creatorDate" => "01/01/1992",
        "creatorFormation" => "Desenvolvedora de Jogos",
        "creatorImg" => "{$path}img/banners/rd2/creatorLogo.jpg",
        "creatorSite" => "https://www.rockstargames.com/br/"
        );
    $game[2] = array(
        "id" => 2,
        "title" => "Cyberpunk 2077",
        "description" => "Cyberpunk 2077 é um RPG de ação e aventura em mundo aberto que se passa em Night City, uma megalópole perigosa...",
        
        "descriptionMid" => "Cyberpunk 2077 é um RPG de ação e aventura em mundo aberto que se passa em Night City, uma megalópole perigosa onde todos são obcecados por poder, glamour e alterações corporais.",
        "descriptionFull" => "Cyberpunk 2077 é um RPG de ação e aventura em mundo aberto ambientado na megalópole de Night City, onde você é um mercenário cyberpunk envolvido em uma intensa luta pela sobrevivência. Com diversas melhorias e conteúdo adicional gratuito, personalize o seu personagem e o seu estilo de jogo conforme aceita trabalhos, construa uma reputação e desbloqueie melhorias. Seus relacionamentos e suas escolhas moldarão a história e o mundo ao seu redor. Aqui nascem as lendas. Qual será a sua?",

        "logoGame01" => "{$path}img/banners/cyberpunk/logoGame01.jpg",
        "banner01" => "{$path}img/banners/cyberpunk/banner01.jpg",
        "banner02" => "{$path}img/banners/cyberpunk/banner02.jpg",
        "screenShot01" => "{$path}img/banners/cyberpunk/screenshot01.jpg",
        "screenShot02" => "{$path}img/banners/cyberpunk/screenshot02.jpg",
        "screenShot03" => "{$path}img/banners/cyberpunk/screenshot03.jpg",
        "screenShot04" => "{$path}img/banners/cyberpunk/screenshot04.jpg",
        "video01" => "",
        "category" => "RPG",
        "categoryLink" => "RPG",
        "modoJogo" => "Um jogador",
        "multiplayer" => "Sem Suporte a on-line",
        "controls" => "Teclado, Controles",
    
        "CPU_Min" => "Core i7-6700 or Ryzen 5 1600",
        "GPU_Min" => "GeForce GTX 1060 6GB or Radeon RX 580 8GB or Arc A380",
        "storage_Min" => "70 GB",
        "memory_Min" => "12gb RAM",
        "SO_Min" => "Windows 10 64-bit",
        "OBS_Min" => "SSD Recomendado",
    
        "CPU_Recomendate" => "Core i7-12700 or Ryzen 7 7800X3D",
        "GPU_Recomendate" => "GeForce RTX 2060 SUPER or Radeon RX 5700 XT or Arc A770",
        "storage_Recomendate" => "70 GB",
        "memory_Recomendate" => "16gb RAM",
        "SO_Recomendate" => "Windows 10 64-bit",
        "OBS_Recomendate" => "SSD Requisitado",
    
        "price" => "R$ 199,90",
        "promo" => "",
        "promoLabel" => "",
        "plataform" => "PC, Xbox Series, PS5",
        "analisesBoa" => "Muito Positivas",
        "analisesNeutra" => "",
        "analisesRuim" => "",
        "privacity" => "https://regulations.cdprojektred.com/en/privacy_policy",
        "userAccept" => "https://regulations.cdprojektred.com/en/user_agreement",
        "pegiInfo" => "18+",
    
        "analise1_img" => "{$path}img/analise01.jpg",
        "analise1_userName" => "Mafi",
        "analise1_recomendacao" => "Recomendado",
        "analise1_naoRecomendacao" => "",
        "analise1_recomendacaoRuim" => "",
        "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise1_data" => "30 DE MAIO",
        "analise1_descricao" => "Começo dizendo que fui um dos que comprou Cyberpunk 2077 na pré-venda do PS4 e, sim, quando surgiu a opção de reembolso, eu pedi sem nem pensar duas vezes. Depois disso, um ano depois, comprei a mídia física de PS4 por 35 reais e tentei jogar no PS5 e, mesmo assim, não rolou. Vendi a mídia física e, em 2023, comprei Cyberpunk 2077 no PC, atualizado no patch 2.0 por 100 pila e AGORA SIM CONSEGUI JOGAR. Vamos lá...",
    
        "analise2_img" => "{$path}img/analise02.jpg",
        "analise2_userName" => "Kosmux",
        "analise2_recomendacao" => "Recomendado",
        "analise2_naoRecomendacao" => "",
        "analise2_recomendacaoRuim" => "",
        "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise2_data" => "8 DE JUNHO",
        "analise2_descricao" => "Cyberpunk é uma maravilha da indústria moderna, com seus gráficos impressionantes, suas animações assustadoramente realistas e imersivas e o mais importante: sua história envolvente e bem escrita, com personagens memoráveis. RPGs assim, onde coisas vão mal, onde o mundo não é um conto-de-fadas, são sempre mais imersivos e prazerosos de jogar, afinal, é mais verossímil a humanidade ter um fim do que explorar o espaço. Os pouquíssimos bugs que ainda existem são mais motivos para rir do que para implicar, são engolidos pelo resto do jogo que é feito com maestria. Experiência inesquecível.",
    
        "analise3_img" => "{$path}img/analise03.jpg",
        "analise3_userName" => "NiGhT",
        "analise3_recomendacao" => "Recomendado",
        "analise3_naoRecomendacao" => "",
        "analise3_recomendacaoRuim" => "",
        "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise3_data" => "19 DE JUNHO",
        "analise3_descricao" => "Night City!!! A Cidade dos Sonhos!!!!",
    
        "analise4_img" => "{$path}img/analise04.jpg",
        "analise4_userName" => "Volmer",
        "analise4_recomendacao" => "",
        "analise4_naoRecomendacao" => "Nao recomendado",
        "analise4_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise4_recomendacaoBoa" => "",
        "analise4_data" => " 19 DE JUNHO",
        "analise4_descricao" => "Mas infelizmente com essa otimização minha experiência está afetada, e assim, com muita dor no coração, não recomendo Cyberpunk 2077 no momento. Segundo as especificações, meu setup era pra rodar o jogo tranquilamente no alto, mas não chega nem perto disso, e no medium/low ainda se complica pra manter os 60 cravados, dropando muito (chegando até menos de 30 em alguns casos) em certas partes da cidade mesmo com a densidade de npcs no médio. Olhando outros comentários sobre o jogo, é fato: está mal otimizado, pequenas variações e pouco uso da máquina ao mudar presets. É algo meio triste, já que a compra do PC foi ditada basicamente por esse jogo que espero a tanto tempo, fora todos os problemas, crunch e adiamentos no processo.",
    
        "gameLink" => "https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
        "realeaseDate" => "9/dez./2020",
        "distributor" => "CD PROJEKT RED",
        "distributorSite" => "https://www.cdprojektred.com/en",
        "creator" => "CD PROJEKT RED",
        "creatorName" => "CD PROJEKT RED",
        "creatorDate" => "01/01/1992",
        "creatorFormation" => "Desenvolvedora de Jogos",
        "creatorImg" => "{$path}img/banners/cyberpunk/creatorLogo.jpg",
        "creatorSite" => "https://www.cdprojektred.com/en"
        );

    $game[3] = array(
        "id" => 3,
        "title" => "iRacing",
        "description" => "Somos o principal jogo de corrida de automobilismo do mundo. Uma associação ao iRacing oferece acesso à mais nova...",
        
        "descriptionMid" => "Somos o principal jogo de corrida de automobilismo do mundo. Uma associação ao iRacing oferece acesso à mais nova forma de automobilismo: corridas pela Internet. As corridas pela Internet são uma maneira divertida, fácil e barata para os fãs e jogadores de corridas aproveitarem a emoção da pista de corrida no conforto de suas casas.",
        "descriptionFull" => "Somos o principal jogo/simulação/jogo de corrida de automobilismo baseado em computador do mundo. A associação ao iRacing.com oferece acesso à mais nova forma de automobilismo competitivo: corridas pela Internet. As corridas pela Internet são uma maneira divertida, fácil e barata para os fãs de corridas, simracers e jogadores aproveitarem a emoção da pista de corrida no conforto de suas casas. Somos o melhor lugar para correr online. Da NASCAR ao World of Outlaws, dos Supercars australianos aos carros esportivos e corridas de Grand Prix, o iRacing tem de tudo. Tudo o que você precisa é de um computador, um volante ou gamepad que simplesmente se conecte à porta USB do seu computador e uma conexão à Internet. iRacing organiza centralmente todas as corridas para você com mais de 150 carros e pistas, 40 séries oficiais, ou você pode optar por hospedar sua própria corrida ou corrida em uma das mais de 800 ligas privadas. iRacing é uma experiência online emocionante que oferece: * A melhor simulação e serviço de corrida online do mundo, com recursos e funcionalidades brilhantes * Competição de corrida frente a frente em um local centralizado e fácil de usar - corrida contra pessoas reais * Superfícies de pista dinâmicas que mudam ao longo de uma corrida, assim como nas corridas do mundo real * Treinos abertos, qualificação, testes, corridas fantasmas, competição de contra-relógio * Team Racing - compartilhe as responsabilidades de direção, localização e equipe de box com seus companheiros de equipe e corra em eventos de até 24 horas de duração * Corrida de Calor * Constantes atualizações automáticas gratuitas e melhorias no serviço * Carros oficialmente licenciados, projetados desde o início em cooperação com equipes de corrida do mundo real e usando a física do mundo real * Réplicas exatas digitalizadas a laser e oficialmente licenciadas das maiores pistas de corrida do mundo * Corridas oficialmente sancionadas e organizadas pela iRacing * Uma comunidade online de entusiastas de corridas com mais de 170.000 pessoas * Organize suas próprias sessões privadas, organize seus próprios torneios * League Racing: crie sua própria série de corridas personalizadas com seus amigos ou junte-se a uma das mais de 800 ligas existentes...",

        "logoGame01" => "{$path}img/banners/iRacing/logoGame01.jpg",
        "banner01" => "{$path}img/banners/iRacing/banner01.jpg",
        "banner02" => "{$path}img/banners/iRacing/banner02.jpg",
        "screenShot01" => "{$path}img/banners/iRacing/screenshot01.jpg",
        "screenShot02" => "{$path}img/banners/iRacing/screenshot02.jpg",
        "screenShot03" => "{$path}img/banners/iRacing/screenshot03.jpg",
        "screenShot04" => "{$path}img/banners/iRacing/screenshot04.jpg",
        "video01" => "",
        "category" => "Simulacao",
        "categoryLink" => "simulator",
        "modoJogo" => "Um jogador",
        "multiplayer" => "Eventos On-line",
        "controls" => "Teclado, Controles, Volante e VR",
    
        "CPU_Min" => "4 core CPU or better | Some examples (but not limited to): AMD FX-6300, Intel Core i5-4430, Intel Core i5-2320, AMD Ryzen 3 1200",
        "GPU_Min" => "A gaming graphics card with at least 4GB of DEDICATED memory | Some examples (but not limited to): Nvidia GeForce GTX 1060 or AMD Radeon 570 or better",
        "storage_Min" => "25 GB",
        "memory_Min" => "16gb RAM",
        "SO_Min" => "Windows 10 64-bit",
        "OBS_Min" => "SSD Recomendado",
    
        "CPU_Recomendate" => "8 core or more CPU (some examples but not limited to: Intel Core 9-10980XE @ 3.0GHz, Intel Core i9-9900KS @ 4.00GHz, AMD Ryzen 9 3900X, or AMD Ryzen 9 3950X)",
        "GPU_Recomendate" => "Gaming graphics card with at least 8GB of DEDICATED memory (some examples but not limited to Nvidia 2080 TI or AMD Radeon VII)",
        "storage_Recomendate" => "100 GB",
        "memory_Recomendate" => "32gb RAM",
        "SO_Recomendate" => "Windows 10 64-bit",
        "OBS_Recomendate" => "SSD Requisitado",
    
        "price" => "GRATUITO",
        "promo" => "",
        "promoLabel" => "",
        "plataform" => "PC",
        "analisesBoa" => "Muito Positivas",
        "analisesNeutra" => "",
        "analisesRuim" => "",
        "privacity" => "https://support.iracing.com/support/solutions",
        "userAccept" => "https://support.iracing.com/support/home",
        "pegiInfo" => "12+",
    
        "analise1_img" => "{$path}img/analise01.jpg",
        "analise1_userName" => "sabota",
        "analise1_recomendacao" => "",
        "analise1_naoRecomendacao" => "Nao recomendado",
        "analise1_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise1_recomendacaoBoa" => "",
        "analise1_data" => "11 DE MARÇO",
        "analise1_descricao" => "Mestres do capitalismo.",
    
        "analise2_img" => "{$path}img/analise02.jpg",
        "analise2_userName" => "abacuque37",
        "analise2_recomendacao" => "Recomendado",
        "analise2_naoRecomendacao" => "",
        "analise2_recomendacaoRuim" => "",
        "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise2_data" => "21 DE MAIO",
        "analise2_descricao" => "Melhor simulador de corrida",
    
        "analise3_img" => "{$path}img/analise03.jpg",
        "analise3_userName" => "Theusma",
        "analise3_recomendacao" => "Recomendado",
        "analise3_naoRecomendacao" => "",
        "analise3_recomendacaoRuim" => "",
        "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise3_data" => "22 DE JUNHO",
        "analise3_descricao" => "Joguinho top... A barreira pra entrar é alta (custo) o que elimina bastante os trolls.",
    
        "analise4_img" => "{$path}img/analise04.jpg",
        "analise4_userName" => "renatoveio",
        "analise4_recomendacao" => "",
        "analise4_naoRecomendacao" => "Nao recomendado",
        "analise4_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise4_recomendacaoBoa" => "",
        "analise4_data" => "3 DE MAIO",
        "analise4_descricao" => "Aplicativo mau feito, vira e mexe da erros doidos, vc tem que executar tal .bat, compra de qualquer coisa demora 1 dia, é mais demorado do que você ia a loja e compra um carro de verdade, hoje que é o unico dia que posso jogar essa semana.. tem mais essa : iracing - erro na execução easy anti-cheat não instalado.",
    
        "gameLink" => "https://store.steampowered.com/app/266410/iRacing/",
        "realeaseDate" => "12/jan./2015",
        "distributor" => "iRacing Motorsport Simulations",
        "distributorSite" => "https://www.cdprojektred.com/en",
        "creator" => "iRacing Motorsport Simulations",
        "creatorName" => "iRacing Motorsport Simulations",
        "creatorDate" => "01/01/1992",
        "creatorFormation" => "Desenvolvedora de Jogos",
        "creatorImg" => "{$path}img/banners/iRacing/creatorLogo.jpg",
        "creatorSite" => "https://www.iracing.com"
        );
    $game[4] = array(
        "id" => 4,
        "title" => "Stardew Valley",
        "description" => "Você herdou a antiga fazenda do seu avô, em Stardew Valley. Com ferramentas de segunda-mão e algumas moedas...",
        
        "descriptionMid" => "Você herdou a antiga fazenda do seu avô, em Stardew Valley. Com ferramentas de segunda-mão e algumas moedas, você parte para dar início a sua nova vida. Será que você vai aprender a viver da terra, a transformar esse matagal em um próspero lar?",
        "descriptionFull" => "Você herdou a antiga fazenda do seu avô, em Stardew Valley. Com ferramentas de segunda-mão e algumas moedas, você parte para dar início a sua nova vida. Será que você vai aprender a viver da terra, a transformar esse matagal em um próspero lar? Crie a fazenda dos seus sonhos! Construa sua fazenda do zero em 1 de 5 mapas diferentes. Domine as técnicas da agropecuária! Crie animais, plantações, máquinas úteis e muito mais. Faça parte de uma comunidade local! Faça amizade com mais de 30 moradores diferentes de Pelican Town. Personalize seu fazendeiro! Escolha entre centenas de opções para modificar seu personagem. Organize-se e crie uma família! Compartilhe sua vida na fazenda em um relacionamento com 1 entre 12 personagens disponíveis. Explore cavernas vastas e misteriosas! Encontre monstros perigosos e tesouros valiosos.",

        "logoGame01" => "{$path}img/banners/stardewValley/logoGame01.jpg",
        "banner01" => "{$path}img/banners/stardewValley/banner01.jpg",
        "banner02" => "{$path}img/banners/stardewValley/banner02.jpg",
        "screenShot01" => "{$path}img/banners/stardewValley/screenshot01.jpg",
        "screenShot02" => "{$path}img/banners/stardewValley/screenshot02.jpg",
        "screenShot03" => "{$path}img/banners/stardewValley/screenshot03.jpg",
        "screenShot04" => "{$path}img/banners/stardewValley/screenshot04.jpg",
        "video01" => "",
        "category" => "RPG",
        "categoryLink" => "RPG",
        "modoJogo" => "Um jogador",
        "multiplayer" => "Eventos On-line",
        "controls" => "Teclado, Controles",
    
        "CPU_Min" => "2 Ghz",
        "GPU_Min" => "256 mb video memory, shader model 3.0+",
        "storage_Min" => "500 MB",
        "memory_Min" => "2 RAM",
        "SO_Min" => "Windows 10 64-bit",
        "OBS_Min" => "",
    
        "CPU_Recomendate" => "2 Ghz",
        "GPU_Recomendate" => "512 mb video memory, shader model 3.0+",
        "storage_Recomendate" => "1 GB",
        "memory_Recomendate" => "4gb RAM",
        "SO_Recomendate" => "Windows 10 64-bit",
        "OBS_Recomendate" => "",
    
        "price" => "R$ 24,99",
        "promo" => "29,99",
        "promoLabel" => "promoLabel",
        "plataform" => "PC",
        "analisesBoa" => "Extremamente Positivas",
        "analisesNeutra" => "",
        "analisesRuim" => "",
        "privacity" => "https://www.stardewvalley.net/privacy/",
        "userAccept" => "https://www.stardewvalley.net/terms/",
        "pegiInfo" => "12+",
    
        "analise1_img" => "{$path}img/analise01.jpg",
        "analise1_userName" => "notyourtypo",
        "analise1_recomendacao" => "Recomendado",
        "analise1_naoRecomendacao" => "",
        "analise1_recomendacaoRuim" => "",
        "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise1_data" => "6 DE JUNHO",
        "analise1_descricao" => "Ignorando todas as minhas obrigações da vida real, só consigo pensar em fazendinha",
    
        "analise2_img" => "{$path}img/analise02.jpg",
        "analise2_userName" => "Loladls",
        "analise2_recomendacao" => "Recomendado",
        "analise2_naoRecomendacao" => "",
        "analise2_recomendacaoRuim" => "",
        "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise2_data" => "15 DE JUNHO",
        "analise2_descricao" => "Unico defeito é que não da pra pegar mulher casada",
    
        "analise3_img" => "{$path}img/analise03.jpg",
        "analise3_userName" => "Cherry",
        "analise3_recomendacao" => "Recomendado",
        "analise3_naoRecomendacao" => "",
        "analise3_recomendacaoRuim" => "",
        "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise3_data" => "6 DE JUNHO",
        "analise3_descricao" => "Eu acho que podia apagar a Abigail do jogo pq eu ja namoro o Sebastian então não faz o menor sentido ela existir pq tipo ele ja é meu tlg? tipo eu acho que ela ta ali só pra gastar memoria eu acho que nós deveriamos todos nos reunirmos e matarmos ela pro bem da nossa memória mas isso é so minha opinião né pessoal, eu posso estar errada apesar de que eu nunca estive em toda minha vida tlg mas né quem sou eu pra falar alguma coisa, fora isso é um jogo muito bom mas falta opção de bloquear as pessoas da vida do nosso namorado.",
    
        "analise4_img" => "{$path}img/analise04.jpg",
        "analise4_userName" => "Benediit0",
        "analise4_recomendacao" => "Recomendado",
        "analise4_naoRecomendacao" => "",
        "analise4_recomendacaoRuim" => "",
        "analise4_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
        "analise4_data" => "23 DE JUNHO",
        "analise4_descricao" => "Se você tiver autismo, JOGUE !",
    
        "gameLink" => "https://store.steampowered.com/app/413150/Stardew_Valley/",
        "realeaseDate" => "26/fev./2016",
        "distributor" => "ConcernedApe",
        "distributorSite" => "https://www.stardewvalley.net",
        "creator" => "ConcernedApe",
        "creatorName" => "ConcernedApe",
        "creatorDate" => "01/01/1992",
        "creatorFormation" => "Desenvolvedora de Jogos",
        "creatorImg" => "{$path}img/banners/stardewValley/creatorLogo.jpg",
        "creatorSite" => "https://www.stardewvalley.net"
        );
    $game[5] = array(
        "id" => 5,
        "title" => "Overwatch® 2",
        "description" => "Overwatch® 2 é um jogo de tiro em equipe aclamado pela crítica, ambientado em um futuro otimista com um...",
        
        "descriptionMid" => "Overwatch® 2 é um jogo de tiro em equipe aclamado pela crítica, ambientado em um futuro otimista com um elenco crescente de heróis. Jogue com seus amigos e entre agora mesmo!",
        "descriptionFull" => "Estamos animados para apresentar o novo programa de E-sports de Overwatch e a Overwatch Champions Series. Assista ao vídeo de atualização e acesse nosso blog para saber mais sobre o que vem aí nos E-sports de Overwatch em 2024. Conheça Venture, a nova adição aos heróis de Dano, disponível para todos. Com seu entusiasmo arqueológico e grande heroísmo, Venture muda o jogo com suas habilidades subterrâneas e dano considerável. Supere seus adversários e desenterre a vitória enquanto cava, mergulha, perfura e causa danos sísmicos massivos para esmagar esperanças e diminuir barras de vida. Viaje pelo mundo e lute pelo futuro em diversos lugares do planeta. Das maravilhas tecnológicas de Busan às ruas nevadas de Toronto, cada mapa conta com objetivos para alcançar, segredos para descobrir e estratégias para explorar.",

        "logoGame01" => "{$path}img/banners/overwatch/logoGame01.jpg",
        "banner01" => "{$path}img/banners/overwatch/banner01.jpg",
        "banner02" => "{$path}img/banners/overwatch/banner02.jpg",
        "screenShot01" => "{$path}img/banners/overwatch/screenshot01.jpg",
        "screenShot02" => "{$path}img/banners/overwatch/screenshot02.jpg",
        "screenShot03" => "{$path}img/banners/overwatch/screenshot03.jpg",
        "screenShot04" => "{$path}img/banners/overwatch/screenshot04.jpg",
        "video01" => "",
        "category" => "Ação",
        "categoryLink" => "action",
        "modoJogo" => "Multijogador",
        "multiplayer" => "Eventos On-line",
        "controls" => "Teclado, Controles",
    
        "CPU_Min" => " Intel® Core™ i3 ou AMD Phenom™ X3 865",
        "GPU_Min" => "Série NVIDIA® GeForce® GTX 600, série AMD Radeon™ HD 7000",
        "storage_Min" => "50 GB",
        "memory_Min" => "6gb RAM",
        "SO_Min" => "Windows 10 64-bit",
        "OBS_Min" => "",
    
        "CPU_Recomendate" => "Intel® Core™ i7 ou AMD Ryzen™ 5",
        "GPU_Recomendate" => "NVIDIA® GeForce® GTX 1060/ GeForce® GTX 1650 ou AMD R9 380/AMD RX 6400 ou Intel® Arc™ A770",
        "storage_Recomendate" => "50 GB",
        "memory_Recomendate" => "8gb RAM",
        "SO_Recomendate" => "Windows 10 64-bit",
        "OBS_Recomendate" => "",
    
        "price" => "GRATUITO",
        "promo" => "",
        "promoLabel" => "",
        "plataform" => "PC, PS5, Xbox Series",
        "analisesBoa" => "",
        "analisesNeutra" => "",
        "analisesRuim" => "Extremamente negativas",
        "privacity" => "https://www.blizzard.com/pt-br/privacy",
        "userAccept" => "https://www.blizzard.com/pt-br/legal/c703cd95-b650-4721-8e77-934c217e9096/termos-de-uso-do-site-da-blizzard",
        "pegiInfo" => "12+",
    
        "analise1_img" => "{$path}img/analise01.jpg",
        "analise1_userName" => "Marsala",
        "analise1_recomendacao" => "",
        "analise1_naoRecomendacao" => "Nao recomendado",
        "analise1_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise1_recomendacaoBoa" => "",
        "analise1_data" => "2 DE JUNHO",
        "analise1_descricao" => "Tenho 1800hrs somando com console e battle.net, posso afirmar, desde 2016 jogo isso.
Nós não damos análises negativas por conta do jogo ser ruim, na realidade ele é ótimo. Nós damos por conta de toda cagada que a Blizzard fez e faz, o jogo nunca mais será o de antigamente, esperem Marvel Rivals ou outro jogo desse nicho, que OW está incurável no momento.",
    
        "analise2_img" => "{$path}img/analise02.jpg",
        "analise2_userName" => "Dud's",
        "analise2_recomendacao" => "",
        "analise2_naoRecomendacao" => "Nao recomendado",
        "analise2_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise2_recomendacaoBoa" => "",
        "analise2_data" => "9 DE JUNHO",
        "analise2_descricao" => "Gosto mto desse jogo, e posso dizer q ele é péssimo",
    
        "analise3_img" => "{$path}img/analise03.jpg",
        "analise3_userName" => "oficialLuke",
        "analise3_recomendacao" => "",
        "analise3_naoRecomendacao" => "Nao recomendado",
        "analise3_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise3_recomendacaoBoa" => "",
        "analise3_data" => "5 DE JUNHO",
        "analise3_descricao" => "Apenas a sombra do que ja foi um dia, a Blizzard fez questao de estragar quase tudo do game original, uma pena, era incrivel!",
    
        "analise4_img" => "{$path}img/analise04.jpg",
        "analise4_userName" => "Maevo77",
        "analise4_recomendacao" => "",
        "analise4_naoRecomendacao" => "Nao recomendado",
        "analise4_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
        "analise4_recomendacaoBoa" => "",
        "analise4_data" => "26 DE JUNHO",
        "analise4_descricao" => "a empresa enfiou o jogo no reto bem fundo deles, eu curtia o jogo, mas a blizzard prefere enfiar um abacaxi na minha bunda doque fazer um jogo balanceado e divertido",
    
        "gameLink" => "https://store.steampowered.com/app/2357570/Overwatch_2/",
        "realeaseDate" => "10/ago./2023",
        "distributor" => "Blizzard Entertainment, Inc.",
        "distributorSite" => "https://www.blizzard.com/pt-br/",
        "creator" => "Blizzard Entertainment, Inc.",
        "creatorName" => "Blizzard Entertainment, Inc.",
        "creatorDate" => "01/01/1992",
        "creatorFormation" => "Desenvolvedora de Jogos",
        "creatorImg" => "{$path}img/banners/overwatch/creatorLogo.jpg",
        "creatorSite" => "https://overwatch.blizzard.com/pt-br/"
        );




        $game[6] = array(
            "id" => 6,
            "title" => "Assetto Corsa",

            "description" => "Assetto Corsa v1.16 apresenta a nova pista digitalizada a laser Laguna Seca, 7 novos carros entre os quais o tão...",
            
            "descriptionMid" => "Assetto Corsa v1.16 apresenta a nova pista digitalizada a laser Laguna Seca, 7 novos carros entre os quais o tão aguardado Alfa Romeo Giulia Quadrifoglio! Verifique o changelog para mais informações!",
            "descriptionFull" => "SIMULADOR DE CORRIDAS DE ÚLTIMA GERAÇÃO
Assetto Corsa possui um motor gráfico DirectX 11 avançado, que reproduz um ambiente imersivo, iluminação dinâmica e materiais e superfícies realistas. O sistema de física avançado é projetado para gerar uma experiência de direção bastante realista, incluindo funções e aspectos de carros reais, nunca antes vistos em outros simuladores de corridas. Isso inclui bandas de rodagem, ciclos de resfriamento, degradação e vesiculação, simulação aerodinâmica altamente avançada, com partes móveis acionáveis em tempo real por canais de telemetria, sistemas híbridos de recuperação cinética e simulação de recuperação de energia. Extremamente detalhado, com opções para um ou diversos jogadores, carros licenciados exclusivos reproduzidos com a maior exatidão possível, graças à cooperação oficial com produtoras de veículos reais.
ASSETTO CORSA foi desenvolvido no KUNOS Simulazioni R&D Office, localizado dentro do circuito internacional de corrida de Vallelunga, o que possibilitou que o jogo fosse desenvolvido conjuntamente com pilotos e equipes de pilotagem reais.",
    
            "logoGame01" => "{$path}img/banners/assettoCorsa/logoGame01.jpg",
            "banner01" => "{$path}img/banners/assettoCorsa/banner01.jpg",
            "banner02" => "{$path}img/banners/assettoCorsa/banner02.jpg",
            "screenShot01" => "{$path}img/banners/assettoCorsa/screenshot01.jpg",
            "screenShot02" => "{$path}img/banners/assettoCorsa/screenshot02.jpg",
            "screenShot03" => "{$path}img/banners/assettoCorsa/screenshot03.jpg",
            "screenShot04" => "{$path}img/banners/assettoCorsa/screenshot04.jpg",
            "video01" => "",
            "category" => "Simulacao",
            "categoryLink" => "simulator",
            "modoJogo" => "Um jogador",
            "multiplayer" => "Eventos On-line",
            "controls" => "Teclado, Controles, Volante e VR",
        
            "CPU_Min" => "AMD Athlon X2 2.8 GHZ, Intel Core 2 Duo 2.4 GHZ",
            "GPU_Min" => "DirectX 10.1 (e.g. AMD Radeon HD 6450, Nvidia GeForce GT 460)",
            "storage_Min" => "15 GB",
            "memory_Min" => "2gb RAM",
            "SO_Min" => "Windows 10 64-bit",
            "OBS_Min" => "",
        
            "CPU_Recomendate" => "AMD Six-Core CPU, Intel Quad-Core CPU",
            "GPU_Recomendate" => "DirectX 11 (e.g. AMD Radeon 290x, Nvidia GeForce GTX 970)",
            "storage_Recomendate" => "30 GB",
            "memory_Recomendate" => "8gb RAM",
            "SO_Recomendate" => "Windows 10 64-bit",
            "OBS_Recomendate" => "",
        
            "price" => "R$ 5,99",
            "promo" => "59,99",
            "promoLabel" => "promoLabel",
            "plataform" => "PC, PS4, Xbox One",
            "analisesBoa" => "Muito Positivas",
            "analisesNeutra" => "",
            "analisesRuim" => "",
            "privacity" => "https://assettocorsa.gg/privacy-policy/",
            "userAccept" => "https://assettocorsa.gg/#newsletter",
            "pegiInfo" => "LIVRE",
        
            "analise1_img" => "{$path}img/analise01.jpg",
            "analise1_userName" => "LGomes",
            "analise1_recomendacao" => "Recomendado",
            "analise1_naoRecomendacao" => "",
            "analise1_recomendacaoRuim" => "",
            "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
            "analise1_data" => "31 DE MAIO",
            "analise1_descricao" => "Assetto Corsa é como ter seu próprio carro de corrida na sala de estar, só que sem o risco de quebrar a mesa de centro. Realismo de tirar o fôlego e uma física que faz você sentir cada curva como se estivesse competindo em Le Mans.",
        
            "analise2_img" => "{$path}img/analise02.jpg",
            "analise2_userName" => "pingu",
            "analise2_recomendacao" => "Recomendado",
            "analise2_naoRecomendacao" => "",
            "analise2_recomendacaoRuim" => "",
            "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
            "analise2_data" => "20 DE JUNHO",
            "analise2_descricao" => "carro acelera = homem feliz",
        
            "analise3_img" => "{$path}img/analise03.jpg",
            "analise3_userName" => "GEME",
            "analise3_recomendacao" => "Recomendado",
            "analise3_naoRecomendacao" => "",
            "analise3_recomendacaoRuim" => "",
            "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
            "analise3_data" => "24 DE MAIO",
            "analise3_descricao" => "Nada vê o nome e assetto corsa mais não tem corsa",
        
            "analise4_img" => "{$path}img/analise04.jpg",
            "analise4_userName" => "roberta",
            "analise4_recomendacao" => "Recomendado",
            "analise4_naoRecomendacao" => "",
            "analise4_recomendacaoRuim" => "",
            "analise4_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
            "analise4_data" => "26 DE MAIO",
            "analise4_descricao" => "Há um ponto em 7.000 RPM onde tudo desaparece. A máquina fica sem peso. Simplesmente desaparece. E tudo o que resta é um corpo se movendo no espaço e no tempo.",
        
            "gameLink" => "https://store.steampowered.com/app/244210/Assetto_Corsa/",
            "realeaseDate" => "19/dez./2014",
            "distributor" => "Kunos Simulazioni",
            "distributorSite" => "https://assettocorsa.gg",
            "creator" => "Kunos Simulazioni",
            "creatorName" => "Kunos Simulazioni",
            "creatorDate" => "01/01/1992",
            "creatorFormation" => "Desenvolvedora de Jogos",
            "creatorImg" => "{$path}img/banners/assettoCorsa/creatorLogo.jpg",
            "creatorSite" => "https://assettocorsa.gg"
            );

            $game[7] = array(
                "id" => 7,
                "title" => "The Witcher 3: Wild Hunt",
                
                "description" => "Você é Geralt de Rívia, mercenário matador de monstros. Você está em um continente devastado pela guerra...",
                
                "descriptionMid" => "Você é Geralt de Rívia, mercenário matador de monstros. Você está em um continente devastado pela guerra e infestado de monstros para você explorar à vontade. Sua tarefa é encontrar Ciri, a Criança da Profecia — uma arma viva que pode alterar a forma do mundo.",
                "descriptionFull" => "Você é Geralt de Rívia, mercenário matador de monstros. O lugar é um continente devastado pela guerra e infestado de monstros que você pode explorar à vontade. Seu contrato atual? Encontrar Ciri, a Criança da Profecia — uma arma viva que pode alterar a forma do mundo.

Atualizado para a versão mais recente, The Witcher 3: Wild Hunt vem com novos recursos e itens, incluindo o Modo Fotografia integrado, espadas, armaduras, aparências alternativas inspiradas na série The Witcher da Netflix e muito mais! Contemple o mundo sombrio de fantasia do Continente como nunca antes! Esta edição de The Witcher 3: Wild Hunt foi aprimorada com inúmeras melhorias visuais e técnicas, inclusive com nível de detalhes elaborado, uma variedade de modificações criadas e recém-desenvolvidas pela comunidade para o jogo, traçado de raios em tempo real e muito mais — especialmente para o desempenho dos PCs mais modernos.",
        
                "logoGame01" => "{$path}img/banners/theWitcher3/logoGame01.jpg",
                "banner01" => "{$path}img/banners/theWitcher3/banner01.jpg",
                "banner02" => "{$path}img/banners/theWitcher3/banner02.jpg",
                "screenShot01" => "{$path}img/banners/theWitcher3/screenshot01.jpg",
                "screenShot02" => "{$path}img/banners/theWitcher3/screenshot02.jpg",
                "screenShot03" => "{$path}img/banners/theWitcher3/screenshot03.jpg",
                "screenShot04" => "{$path}img/banners/theWitcher3/screenshot04.jpg",
                "video01" => "",
                "category" => "RPG",
                "categoryLink" => "RPG",
                "modoJogo" => "Um Jogador",
                "multiplayer" => "Sem suporte a On-line",
                "controls" => "Teclado, Controles",
            
                "CPU_Min" => "Intel CPU Core i5-2500K 3.3GHz / AMD A10-5800K APU (3.8GHz)",
                "GPU_Min" => "Nvidia GPU GeForce GTX 660 / AMD GPU Radeon HD 7870",
                "storage_Min" => "50 GB",
                "memory_Min" => "6gb RAM",
                "SO_Min" => "Windows 10 64-bit",
                "OBS_Min" => "",
            
                "CPU_Recomendate" => "Intel Core i5-7400 / Ryzen 5 1600",
                "GPU_Recomendate" => "Nvidia GTX 1070 / Radeon RX 480",
                "storage_Recomendate" => "50 GB",
                "memory_Recomendate" => "8gb RAM",
                "SO_Recomendate" => "Windows 10 64-bit",
                "OBS_Recomendate" => "",
            
                "price" => "R$ 129,99",
                "promo" => "",
                "promoLabel" => "",
                "plataform" => "PC, PS5, Xbox Series",
                "analisesBoa" => "Extremamente positivas",
                "analisesNeutra" => "",
                "analisesRuim" => "",
                "privacity" => "https://regulations.cdprojektred.com/en/privacy_policy",
                "userAccept" => "https://regulations.cdprojektred.com/en/user_agreement",
                "pegiInfo" => "16+",
            
                "analise1_img" => "{$path}img/analise01.jpg",
                "analise1_userName" => "LGDMF",
                "analise1_recomendacao" => "Recomendado",
                "analise1_naoRecomendacao" => "",
                "analise1_recomendacaoRuim" => "",
                "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                "analise1_data" => "5 DE JUNHO",
                "analise1_descricao" => "Confesso que já havia dropado o jogo no Xbox One em 2021 por conta dos 30 FPS, mas no PC esse jogo muda completamente por conta da taxa de quadros maior e a imensa quantidade de mods disponíveis. Embora eu não tenha curtido muito a gameplay, o mundo aberto do game é um dos melhores já feitos, a trilha sonora é ótima e a história do jogo te prende do início ao fim. Recomendo",
            
                "analise2_img" => "{$path}img/analise02.jpg",
                "analise2_userName" => "JhonWick",
                "analise2_recomendacao" => "Recomendado",
                "analise2_naoRecomendacao" => "",
                "analise2_recomendacaoRuim" => "",
                "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                "analise2_data" => "2 DE JUNHO",
                "analise2_descricao" => "O jogo é ótimo, poucos jogos receberam tantos detalhes e atenção. O mundo é belo e perigoso, é muito interessante as histórias contadas ao longo da trama. Eu compraria com certeza outros jogos com esse nível de qualidade. Não vi muitos bugs nem outros problemas. Ah a história também é longa e com muitas, muitas secundarias, não vai faltar horas de jogo então valo o preço.",
            
                "analise3_img" => "{$path}img/analise03.jpg",
                "analise3_userName" => "Ryanzxs",
                "analise3_recomendacao" => "Recomendado",
                "analise3_naoRecomendacao" => "",
                "analise3_recomendacaoRuim" => "",
                "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                "analise3_data" => "15 DE JUNHO",
                "analise3_descricao" => "BAOOO DEMAIS UAII",
            
                "analise4_img" => "{$path}img/analise04.jpg",
                "analise4_userName" => "Jefferson",
                "analise4_recomendacao" => "Recomendado",
                "analise4_naoRecomendacao" => "",
                "analise4_recomendacaoRuim" => "",
                "analise4_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                "analise4_data" => "1 DE MAIO",
                "analise4_descricao" => "Eu não quero fazer uma análise, quero dizer obrigado.
Agradeço por estar vivo e poder jogar esta obra, por toda a história que acompanhei
e por todos os personagens que conheci jogando este jogo.",
            
                "gameLink" => "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
                "realeaseDate" => "18/mai./2015",
                "distributor" => "CD PROJEKT RED",
                "distributorSite" => "https://www.blizzard.com/pt-br/",
                "creator" => "CD PROJEKT RED",
                "creatorName" => "CD PROJEKT RED",
                "creatorDate" => "01/01/1992",
                "creatorFormation" => "Desenvolvedora de Jogos",
                "creatorImg" => "{$path}img/banners/theWitcher3/creatorLogo.jpg",
                "creatorSite" => "https://overwatch.blizzard.com/pt-br/"
                );

                $game[8] = array(
                    "id" => 8,
                    "title" => "DARK SOULS™: REMASTERED",
                    "description" => "Mas então, fez-se o fogo. Experimente novamente o jogo aclamado pela crítica e definidor de gênero...",
                    
                    "descriptionMid" => "Mas então, fez-se o fogo. Experimente novamente o jogo aclamado pela crítica e definidor de gênero que foi o início tudo. Belamente remasterizado, volte a Lordran com detalhes em alta definição a 60fps.",
                    "descriptionFull" => "Mas então, fez-se o fogo. Experimente novamente o jogo aclamado pela crítica e definidor de gênero que foi o início tudo. Belamente remasterizado, volte a Lordran com detalhes em alta definição a 60fps.
Dark Souls Remastered inclui o jogo principal e o DLC Artorias do Abismo.
Recursos principais:
• Universo profundo e sombrio
• Cada fim é um novo começo
• Riqueza e possibilidades de jogabilidade
• Noção de aprendizado, domínio e conquista
• O modo do multijogador (até 6 jogadores com servidores dedicados)",
            
                    "logoGame01" => "{$path}img/banners/darkSouls/logoGame01.jpg",
                    "banner01" => "{$path}img/banners/darkSouls/banner01.jpg",
                    "banner02" => "{$path}img/banners/darkSouls/banner02.jpg",
                    "screenShot01" => "{$path}img/banners/darkSouls/screenshot01.jpg",
                    "screenShot02" => "{$path}img/banners/darkSouls/screenshot02.jpg",
                    "screenShot03" => "{$path}img/banners/darkSouls/screenshot03.jpg",
                    "screenShot04" => "{$path}img/banners/darkSouls/screenshot04.jpg",
                    "video01" => "",
                    "category" => "Ação",
                    "categoryLink" => "Action",
                    "modoJogo" => "Um Jogador",
                    "multiplayer" => "Sem suporte a On-line",
                    "controls" => "Teclado, Controles",
                
                    "CPU_Min" => "Intel Core i5-2300 2.8 GHz / AMD FX-6300, 3.5 GHz",
                    "GPU_Min" => "GeForce GTX 460, 1 GB / Radeon HD 6870, 1 GB",
                    "storage_Min" => "8 GB",
                    "memory_Min" => "6gb RAM",
                    "SO_Min" => "Windows 10 64-bit",
                    "OBS_Min" => "",
                
                    "CPU_Recomendate" => "Intel Core i5-4570 3.2 GHz / AMD FX-8350 4.2 GHz",
                    "GPU_Recomendate" => "GeForce GTX 660, 2 GB / Radeon HD 7870, 2 GB",
                    "storage_Recomendate" => "8 GB",
                    "memory_Recomendate" => "8gb RAM",
                    "SO_Recomendate" => "Windows 10 64-bit",
                    "OBS_Recomendate" => "",
                
                    "price" => "R$ 154,90",
                    "promo" => "",
                    "promoLabel" => "",
                    "plataform" => "PC, PS5, Xbox Series",
                    "analisesBoa" => "Muito positivas",
                    "analisesNeutra" => "",
                    "analisesRuim" => "",
                    "privacity" => "https://www.bandainamcoent.com/pt_br/legal/privacy",
                    "userAccept" => "https://www.bandainamcoent.com/pt_br/legal/terms",
                    "pegiInfo" => "14+",
                
                    "analise1_img" => "{$path}img/analise01.jpg",
                    "analise1_userName" => "Farofa",
                    "analise1_recomendacao" => "",
                    "analise1_naoRecomendacao" => "Nao recomendado",
                    "analise1_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
                    "analise1_recomendacaoBoa" => "",
                    "analise1_data" => "18 DE JUNHO",
                    "analise1_descricao" => "amo ds1 mas ele esta muito caro então recomendo pirataria",
                
                    "analise2_img" => "{$path}img/analise02.jpg",
                    "analise2_userName" => "Lambimia",
                    "analise2_recomendacao" => "Recomendado",
                    "analise2_naoRecomendacao" => "",
                    "analise2_recomendacaoRuim" => "",
                    "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                    "analise2_data" => "12 DE JUNHO",
                    "analise2_descricao" => "Nunca tinha jogado nenhum souls like, mas esse aqui é top top, e me deu vontade de jogar os outros tb. Pra mim os mapas, e o caminho até os chefes foram mais complicados do que a batalha contra eles (um ou outro só que deu trabalho). Espere a promoção e compre. Por que 154 reais tá caro demais.",
                
                    "analise3_img" => "{$path}img/analise03.jpg",
                    "analise3_userName" => "xibiu",
                    "analise3_recomendacao" => "Recomendado",
                    "analise3_naoRecomendacao" => "",
                    "analise3_recomendacaoRuim" => "",
                    "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                    "analise3_data" => "11 DE JUNHO",
                    "analise3_descricao" => "não tenho palavras pra dizer a respeito da minha primeira experiência com o soulslike que ditou um gênero INTEIRO. o jogo é extremamente frustrante mas por algum motivo essa frustração é um combustível do caraio pra você querer continuar e termina o jogo.",
                
                    "analise4_img" => "{$path}img/analise04.jpg",
                    "analise4_userName" => "Tiruliru",
                    "analise4_recomendacao" => "",
                    "analise4_naoRecomendacao" => "Nao recomendado",
                    "analise4_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
                    "analise4_recomendacaoBoa" => "",
                    "analise4_data" => "6 DE FEVEREIRO",
                    "analise4_descricao" => "O jogo é bom pra krl, um dos melhores da geração passada, mas 130 conto num remaster que não melhora quase nada comparado ao original não vale a pena nem f*dendo. Eu comprei a key na Nuuvem por 65 pila e ainda achei caro. O dia q o preço baixar pra uns 50/40 pila vale a pena (provável que esse dia nunca chegue, plena summer sale e os sujeito n dão 1% de desconto).",
                
                    "gameLink" => "https://store.steampowered.com/app/570940/DARK_SOULS_REMASTERED/",
                    "realeaseDate" => "23/mai./2018",
                    "distributor" => "FromSoftware, Inc",
                    "distributorSite" => "https://www.bandainamcoent.com",
                    "creator" => "FromSoftware, Inc",
                    "creatorName" => "FromSoftware, Inc",
                    "creatorDate" => "01/01/1992",
                    "creatorFormation" => "Desenvolvedora de Jogos",
                    "creatorImg" => "{$path}img/banners/darkSouls/creatorLogo.jpg",
                    "creatorSite" => "https://www.bandainamcoent.com"
                    );

                    $game[9] = array(
                        "id" => 9,
                        "title" => "Sons Of The Forest",
                        "description" => "Mas então, fez-se o fogo. Experimente novamente o jogo aclamado pela crítica e definidor de gênero...",
                        
                        "description" => "Enviado para encontrar um bilionário desaparecido em uma ilha remota, você se encontra em uma...",
                        
                        "descriptionMid" => "Enviado para encontrar um bilionário desaparecido em uma ilha remota, você se encontra em uma paisagem infernal infestada de canibais. Crie, construa e lute para sobreviver, sozinho ou com amigos, neste novo e aterrorizante simulador de terror de sobrevivência em mundo aberto.",
                        "descriptionFull" => "Enviado para encontrar um bilionário desaparecido em uma ilha remota, você se encontra em uma paisagem infernal infestada de canibais. Crie, construa e lute para sobreviver, sozinho ou com amigos, neste novo e aterrorizante simulador de terror de sobrevivência em mundo aberto. Experimente total liberdade para enfrentar o mundo como quiser. Você decide o que fazer, para onde ir e a melhor forma de sobreviver. Não há nenhum NPC gritando ordens para você ou dando-lhe missões que você não deseja realizar. Você dá as ordens e escolhe o que acontece a seguir.",
                
                        "logoGame01" => "{$path}img/banners/theForest/logoGame01.jpg",
                        "banner01" => "{$path}img/banners/theForest/banner01.jpg",
                        "banner02" => "{$path}img/banners/theForest/banner02.jpg",
                        "screenShot01" => "{$path}img/banners/theForest/screenshot01.jpg",
                        "screenShot02" => "{$path}img/banners/theForest/screenshot02.jpg",
                        "screenShot03" => "{$path}img/banners/theForest/screenshot03.jpg",
                        "screenShot04" => "{$path}img/banners/theForest/screenshot04.jpg",
                        "video01" => "",
                        "category" => "Sobrevivencia",
                        "categoryLink" => "survival",
                        "modoJogo" => "Um Jogador",
                        "multiplayer" => "Cooperativo On-line",
                        "controls" => "Teclado, Controles",
                    
                        "CPU_Min" => "INTEL CORE I5-8400 or AMD RYZEN 3 3300X",
                        "GPU_Min" => "NVIDIA GeForce GTX 1060 3GB or AMD Radeon RX 570 4GB",
                        "storage_Min" => "20 GB",
                        "memory_Min" => "12gb RAM",
                        "SO_Min" => "Windows 10 64-bit",
                        "OBS_Min" => "",
                    
                        "CPU_Recomendate" => "INTEL CORE I7-8700K or AMD RYZEN 5 3600X",
                        "GPU_Recomendate" => "NVIDIA GeForce 1080Ti or AMD Radeon RX 5700 XT",
                        "storage_Recomendate" => "20 GB",
                        "memory_Recomendate" => "16gb RAM",
                        "SO_Recomendate" => "Windows 10 64-bit",
                        "OBS_Recomendate" => "",
                    
                        "price" => "R$ 88,99",
                        "promo" => "",
                        "promoLabel" => "",
                        "plataform" => "PC, PS5, Xbox Series",
                        "analisesBoa" => "Muito positivas",
                        "analisesNeutra" => "",
                        "analisesRuim" => "",
                        "privacity" => "https://endnightgames.com/about",
                        "userAccept" => "https://endnightgames.com/contact",
                        "pegiInfo" => "16+",
                    
                        "analise1_img" => "{$path}img/analise01.jpg",
                        "analise1_userName" => "perfection",
                        "analise1_recomendacao" => "Recomendado",
                        "analise1_naoRecomendacao" => "",
                        "analise1_recomendacaoRuim" => "",
                        "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                        "analise1_data" => "16 DE JUNHO",
                        "analise1_descricao" => "Viver no interior de Pernambuco em casa de barro e a base de vela bebendo água no rio que fica à 500 metros da sua casa é mais fácil que jogar esse jogo na maior dificuldade",
                    
                        "analise2_img" => "{$path}img/analise02.jpg",
                        "analise2_userName" => "Sujiro",
                        "analise2_recomendacao" => "Recomendado",
                        "analise2_naoRecomendacao" => "",
                        "analise2_recomendacaoRuim" => "",
                        "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                        "analise2_data" => "4 DE JUNHO",
                        "analise2_descricao" => "morre, passa medo, morre, pega uma doze, mata bixo, morre pra bixo que nao morre pra doze, nunca passei tanta raiva. Recomendo 100%",
                    
                        "analise3_img" => "{$path}img/analise03.jpg",
                        "analise3_userName" => "Ochiro",
                        "analise3_recomendacao" => "Recomendado",
                        "analise3_naoRecomendacao" => "",
                        "analise3_recomendacaoRuim" => "",
                        "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                        "analise3_data" => "30 DE MAIO",
                        "analise3_descricao" => "Simulador perfeito de como é sobreviver no interior de Minas Gerais.",
                    
                        "analise4_img" => "{$path}img/analise04.jpg",
                        "analise4_userName" => "Jucelino",
                        "analise4_recomendacao" => "",
                        "analise4_naoRecomendacao" => "Nao recomendado",
                        "analise4_recomendacaoRuim" => "<i class='analiseRuim bi bi-hand-thumbs-down-fill'></i>",
                        "analise4_recomendacaoBoa" => "",
                        "analise4_data" => "24 DE FEVEREIRO",
                        "analise4_descricao" => "Primeiramente quero deixar claro que gostei muito do primeiro jogo e que eu estava completamente ansioso para jogar a continuação, porém tenho que ser sincero e não apenas analisar o jogo baseado no quanto eu gostei do primeiro The Forest.
Já começo te deixando bem claro que todo o conteúdo do jogo até agora leva no máximo 3 horas para se obter, mas aí você me diz (a mas o jogo esta em acesso antecipado). Poxa gente, pagar 90 reais em um jogo que tenta se garantir na nostalgia e nos gráficos..,. me frustra.",
                    
                        "gameLink" => "https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/",
                        "realeaseDate" => "22/fev./2024",
                        "distributor" => "Endnight Games Ltd",
                        "distributorSite" => "https://endnightgames.com",
                        "creator" => "Endnight Games Ltd",
                        "creatorName" => "Endnight Games Ltd",
                        "creatorDate" => "01/01/1992",
                        "creatorFormation" => "Desenvolvedora de Jogos",
                        "creatorImg" => "{$path}img/banners/theForest/creatorLogo.jpg",
                        "creatorSite" => "https://endnightgames.com"
                        );
    

                        $game[10] = array(
                            "id" => 10,
                            "title" => "Assetto Corsa Competizione",
                

                            "description" => "Assetto Corsa Competizione é o novo jogo oficial do Blancpain GT Series. Graças à qualidade extraordinária...",
                            
                            "descriptionMid" => "Assetto Corsa Competizione é o novo jogo oficial do Blancpain GT Series. Graças à qualidade extraordinária da simulação, o jogo permitirá que você experimente a atmosfera real do campeonato homologado pela FIA GT3, competindo contra motoristas, equipes, carros e circuitos oficiais.",
                            "descriptionFull" => "Assetto Corsa Competizione é o novo jogo oficial do Blancpain GT Series.
Graças à qualidade extraordinária da simulação, o jogo permitirá que você experimente a atmosfera real do campeonato GT3, competindo contra motoristas, equipes, carros e circuitos oficiais reproduzidos no jogo com o mais alto nível de precisão já obtido.
Corridas de Velocidade, Resistência e 24 Horas de Spa ganharão vida com um nível de realismo incrível, tanto no modo para um único jogador quanto para multijogadores.
Assetto Corsa Competizione contará com a Temporada 2018 do Blancpain GT Series e também incluirá a Temporada 2019, que será fornecida como uma atualização gratuita durante o Verão de 2019.
O Assetto Corsa Competizione é o resultado da união da larga experiência do KUNOS Simulazioni com a tecnologia do Unreal Engine 4, capaz de reproduzir gráficos, condições climáticas, corridas noturnas, captura de movimentos e animações fotorrealistas, definindo um novo padrão em termos de imersão no comando de veículos, graças a seus modelos de pneus e aerodinâmica aprimorados.
Projetado para inovar, o Assetto Corsa Competizione será usado na promoção de eSports, levando jogadores ao coração do Blancpain GT Series e oferecendo a eles o comando de Ferraris, Lamborghinis, McLarens e vários outros conceituados carros de corrida GT. Tudo isso reproduzido com um impressionante nível de detalhes.",
                    
                            "logoGame01" => "{$path}img/banners/assettoCorsaCompetizione/logoGame01.jpg",
                            "banner01" => "{$path}img/banners/assettoCorsaCompetizione/banner01.jpg",
                            "banner02" => "{$path}img/banners/assettoCorsaCompetizione/banner02.jpg",
                            "screenShot01" => "{$path}img/banners/assettoCorsaCompetizione/screenshot01.jpg",
                            "screenShot02" => "{$path}img/banners/assettoCorsaCompetizione/screenshot02.jpg",
                            "screenShot03" => "{$path}img/banners/assettoCorsaCompetizione/screenshot03.jpg",
                            "screenShot04" => "{$path}img/banners/assettoCorsaCompetizione/screenshot04.jpg",
                            "video01" => "",
                            "category" => "Simulacao",
                            "categoryLink" => "simulator",
                            "modoJogo" => "Um jogador",
                            "multiplayer" => "Eventos On-line",
                            "controls" => "Teclado, Controles, Volante e VR",
                        
                            "CPU_Min" => "AMD Athlon X2 2.8 GHZ, Intel Core 2 Duo 2.4 GHZ",
                            "GPU_Min" => "DirectX 10.1 (e.g. AMD Radeon HD 6450, Nvidia GeForce GT 460)",
                            "storage_Min" => "15 GB",
                            "memory_Min" => "2gb RAM",
                            "SO_Min" => "Windows 10 64-bit",
                            "OBS_Min" => "",
                        
                            "CPU_Recomendate" => "AMD Six-Core CPU, Intel Quad-Core CPU",
                            "GPU_Recomendate" => "DirectX 11 (e.g. AMD Radeon 290x, Nvidia GeForce GTX 970)",
                            "storage_Recomendate" => "30 GB",
                            "memory_Recomendate" => "8gb RAM",
                            "SO_Recomendate" => "Windows 10 64-bit",
                            "OBS_Recomendate" => "",
                        
                            "price" => "R$ 47,70",
                            "promo" => "159,00",
                            "promoLabel" => "promoLabel",
                            "plataform" => "PC, PS4, Xbox One",
                            "analisesBoa" => "Muito Positivas",
                            "analisesNeutra" => "",
                            "analisesRuim" => "",
                            "privacity" => "https://assettocorsa.gg/privacy-policy/",
                            "userAccept" => "https://assettocorsa.gg/#newsletter",
                            "pegiInfo" => "LIVRE",
                        
                            "analise1_img" => "{$path}img/analise01.jpg",
                            "analise1_userName" => "hrcarazatto",
                            "analise1_recomendacao" => "Recomendado",
                            "analise1_naoRecomendacao" => "",
                            "analise1_recomendacaoRuim" => "",
                            "analise1_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                            "analise1_data" => "31 DE MAIO",
                            "analise1_descricao" => "Bons gráficos, desafiador na medida certa. Excelente simulador de GT! Jogo com o Logitech g923 e me divirto muito!",
                        
                            "analise2_img" => "{$path}img/analise02.jpg",
                            "analise2_userName" => "mamaduck",
                            "analise2_recomendacao" => "Recomendado",
                            "analise2_naoRecomendacao" => "",
                            "analise2_recomendacaoRuim" => "",
                            "analise2_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                            "analise2_data" => "14 DE JUNHO",
                            "analise2_descricao" => "Jogo extremamente amigável para quem vai jogar no controle, as assistências ajudam demais! recomendo",
                        
                            "analise3_img" => "{$path}img/analise03.jpg",
                            "analise3_userName" => "juniorschr",
                            "analise3_recomendacao" => "Recomendado",
                            "analise3_naoRecomendacao" => "",
                            "analise3_recomendacaoRuim" => "",
                            "analise3_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                            "analise3_data" => "2 DE MAIO",
                            "analise3_descricao" => "Definitivamente um dos melhores jogos como porta de entrada para o automobilismo virtual, se você tem um volante e quer começar nos simuladores, pode vim para o ACC que o negocio é bom msm",
                        
                            "analise4_img" => "{$path}img/analise04.jpg",
                            "analise4_userName" => "FR4NC4",
                            "analise4_recomendacao" => "Recomendado",
                            "analise4_naoRecomendacao" => "",
                            "analise4_recomendacaoRuim" => "",
                            "analise4_recomendacaoBoa" => "<i class='analiseBoa bi bi-hand-thumbs-up-fill'></i>",
                            "analise4_data" => "24 DE ABRIL",
                            "analise4_descricao" => "Melhor otimizado para VR que seu antecessor, porem só tem corrida GT, isso não não e um ponto negativo pois o jogo ainda e muito bom de se jogar com bastante variedade de pistas e carros, para quem pode compras as dlcs fica ainda melhor.",
                        
                            "gameLink" => "https://store.steampowered.com/app/805550/Assetto_Corsa_Competizione/",
                            "realeaseDate" => "29/mai./2019",
                            "distributor" => "Kunos Simulazioni",
                            "distributorSite" => "https://assettocorsa.gg",
                            "creator" => "Kunos Simulazioni",
                            "creatorName" => "Kunos Simulazioni",
                            "creatorDate" => "01/01/1992",
                            "creatorFormation" => "Desenvolvedora de Jogos",
                            "creatorImg" => "{$path}img/banners/assettoCorsaCompetizione/creatorLogo.jpg",
                            "creatorSite" => "https://assettocorsa.gg"
                            );
                


    echo json_encode($game);



?>

